### PR TITLE
Drawer showing based on different logged in user type

### PR DESCRIPTION
**Pull request by mandy169**
Only "admin" can access to three drawer items, while the rest only access to two.

The correct rendering for "admin"  is as below,
image

The correct rendering for "patient"  is as below,
image

### CODE REVIEW

**Comment by mandy169** [comment]
Fixed

**Comment by mandy169** [comment]
The random bug fixed.

**Comment by QMuncaster** [comment]
looks good to me but didn't look in detail :)

**Comment by omarkhs** [comment]
good to go!

**Pull request merged**
